# Bun workspace configuration
[install]
# Automatically install peer dependencies
auto = true

# Use exact versions for better reproducibility  
exact = true


[test]
# Test configuration for Bun
coverage = true
timeout = 5000